// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ2crt_84mXe7LJv1JvhczCfPfH4Z4MlQ',
    appId: '1:253034586382:web:7e12297072cd0667f8b75f',
    messagingSenderId: '253034586382',
    projectId: 'skillvalidationapp',
    authDomain: 'skillvalidationapp.firebaseapp.com',
    storageBucket: 'skillvalidationapp.firebasestorage.app',
    measurementId: 'G-NKTF1HZR0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN4UIDnaopUSUgJu_Rx2UQIMQdEiVXhfc',
    appId: '1:253034586382:android:6ee157d1fd742329f8b75f',
    messagingSenderId: '253034586382',
    projectId: 'skillvalidationapp',
    storageBucket: 'skillvalidationapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9H-5itVi-3_oMEue2GW1Cqre_NvGwlAY',
    appId: '1:253034586382:ios:64efaba77943ba9bf8b75f',
    messagingSenderId: '253034586382',
    projectId: 'skillvalidationapp',
    storageBucket: 'skillvalidationapp.firebasestorage.app',
    iosBundleId: 'com.example.skillValidationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9H-5itVi-3_oMEue2GW1Cqre_NvGwlAY',
    appId: '1:253034586382:ios:64efaba77943ba9bf8b75f',
    messagingSenderId: '253034586382',
    projectId: 'skillvalidationapp',
    storageBucket: 'skillvalidationapp.firebasestorage.app',
    iosBundleId: 'com.example.skillValidationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ2crt_84mXe7LJv1JvhczCfPfH4Z4MlQ',
    appId: '1:253034586382:web:8d39c0a16031a732f8b75f',
    messagingSenderId: '253034586382',
    projectId: 'skillvalidationapp',
    authDomain: 'skillvalidationapp.firebaseapp.com',
    storageBucket: 'skillvalidationapp.firebasestorage.app',
    measurementId: 'G-VB7ZR3JQLE',
  );

}